config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  get 'pages/about'

  get 'pages/contact'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :contacts
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
    @last3 = Article.last(3)
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :authenticate_user!
   
   def create
       @article = Article.find(params[:article_id])
       @comment = @article.comments.create(params_comment)
       @comment.user_id = current_user.id if current_user
       
       if @comment.save
           redirect_to article_path(@article), notice: "Added a comment"
       else
           render :new
       end
   end
   
   def update
       @article = Article.find(params[:article_id])
       @comment = @article.comments.find(params[:id])
       
       if @comment.update(params_comment)
           redirect_to article_path(@article), notice: "Comment was created"
       else
           redirect_to :edit
       end
   end
   
   def edit
       @article = Article.find(params[:article_id])
       @comment = @article.comments.find(params[:id])
   end
   
   def destroy
       @article = Article.find(params[:article_id])
       @comment = @article.comments.find(params[:id])
       @comment.destroy
       redirect_to article_path(@article), notice: "Article has been deleted"
   end
   
   private
    def params_comment
       params.require(:comment).permit(:body) 
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
   def new
    @contact = Contact.new
   end
   
   def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      redirect_to root_path
      name = params[:contact][:name]
      email = params[:contact][:email]
      message = params[:contact][:message]
      ContactMailer.contact_email(name, email, message).deliver
      flash[:success] = "Thanks for message we will be in touch shortly"
    else
      redirect_to pages_contact_path
      flash[:danger] = "Oop, there's problem please fill out all the field"
    end
   end
   
   private
   
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if current_user
      redirect_to articles_path
    end
    @articles = Article.last(5)
  end

  def about
  end

  def contact
    @contact = Contact.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
   
   private
   
    def sign_up_params
       params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname) 
    end
    
    def account_update_params
       params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :username, :firstname, :lastname) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<br>

<%= link_to "Edit", article_path %> |
<%= link_to "Back", articles_path %>

app/views/articles/index.html.erb
<div class='row'>
    <div class='col-md-9'>
        <h1>All Articles</h1>

        <table class='table table-striped'>
            <thead>
                <th>Title</th>
                <th>Author</th>
                <th>Body</th>
                <th colspan='3'></th>
            </thead>
            
            <tbody>
                <% @articles.each do |article| %>
                    <tr>
                        <td><%= article.title %></td>
                        <td><%= article.user.username %></td>
                        <td><%= article.body %></td>
                        <td><%= link_to "Show", article_path(article) %></td>
                        <td><%= link_to "Edit", edit_article_path(article) %></td>
                        <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    
    <div class='col-md-3'>
        <div class="well">
           <h4>Recent Articles</h4>
            <% @last3.each do |article| %>
              Created by <%= article.user.username %><br>
              <strong><%= link_to article.title, article %></strong>
              <p><%= truncate(article.body) %></p>
            <% end %>
        </div>
    </div>
    
</div>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1 style="font-size: 62.5px;">  
         <%= @article.title %>
        </h1>

        <!-- Author -->
        <p class="lead">
          <%= @article.user.username %>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Was Posted: 
     

        <hr>

        <!-- Preview Image -->
        

        <!-- Post Content -->
          <%= @article.body %>
       
        <hr>

        <!-- Blog Comments -->
        <%= render @article.comments %>
        <!-- Comments Form -->
       
        <%= render 'comments/form' %>  
        <div class="well">
          
        </div>

        <hr>

        <!-- Posted Comments -->

        <!-- Comment -->



    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        

        <!-- Blog Categories Well -->
        

        <!-- Side Widget Well -->
        <div class="well">
          <h4></h4>
  
        </div>

    </div>

</div>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="media">
    <div class="pull-left">
        
        <%= comment.user.username %>
       
    </div>
    <div class="media-body">
        <p class="media-heading pull-right">
          <%= time_ago_in_words(comment.created_at) %>
        </p><br />
        <%= comment.body %>
       
    </div>
</div>


<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>

<%= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/comments/_form.html.erb
<%= simple_form_for([@article, @article.comments.build]) do |f| %>
    
    <%= f.input :body %>
    <%= f.submit "Post your comment" %>
    
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= simple_form_for([@article, @comment]) do |f| %>
    
    <%= f.input :body %>
    <%= f.submit "Post your comment" %>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %> <span class="sr-only">(current)</span></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About Us", pages_about_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
        <li><%= link_to "Create New Article", new_article_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username if current_user %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if !current_user %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li role="separator" class="divider"></li>
            <% else %>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= bootstrap_flash %>

<div class='container'>
  <%= yield %>
</div>

<% if !current_user %>
<footer class="footer-distributed">
  <div class="footer-left">
    <h3>Company<span>logo</span></h3>
      <p class="footer-links">
        <a href="#">Home</a>
        .
        <a href="#">Blog</a>
        .
        <a href="#">Pricing</a>
        .
        <a href="#">About</a>
        .
        <a href="#">Faq</a>
        .
        <a href="#">Contact</a>
      </p>
      <p class="footer-company-name">Company Name &copy; 2015</p>
      <div class="footer-icons">
        <a href="#"><i class="fa fa-facebook"></i></a>
        
        <a href="#"><i class="fa fa-twitter"></i></a>
        
        <a href="#"><i class="fa fa-linkedin"></i></a>
        
        <a href="#"><i class="fa fa-github"></i></a>
      </div>
  </div>
  
  <div class="footer-right">
    <p>Contact Us</p>
      <form action="#" method="post">
        <input type="text" name="email" placeholder="Email" />
        <textarea name="message" placeholder="Message"></textarea>
        <button>Send</button>
      </form>
  </div>
</footer>
<% else %>

<footer class="footer-distributed">
  <div class="footer-right">
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
  </div>
  <div class="footer-left">
    <p class="footer-links">
      <%#= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
      <%#= link_to "About Us", pages_about_path, class: "page-scroll" %>
    </p>
    <p> </p>
  </div>
</footer>

<% end %>

</body>
</html>

app/views/pages/_mailer.html.erb
<div class='row'>
    <div class='col-md-4 col-md-offset-4'>
        <div class='well'>
            <%= simple_form_for @contact do |f| %>
                <%= f.input :name %>
                <%= f.input :email %>
                <%= f.input :message %>
                <%= f.submit "Get in touch", class: 'btn btn-default' %>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<div class='row'>
    <div class='col-lg-12 text-center'>
        <h1>Contact Us</h1>
        
        <%= render 'pages/mailer' %>
    </div>
</div>

app/views/pages/index.html.erb
<div class='row'>
  <div class="col-md-8">
    <div class="jumbotron">
        <h1>Hello, world!</h1>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>
  </div>
  
  <div class="col-md-4">
   <!-- Blog Search Well -->
    <div class="well">
     <h4>Blog Search</h4>
      <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
          <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
 <!-- /.input-group -->
    </div>
 <!-- Blog Categories Well -->
  <div class="well">
  <h4>Blog Categories</h4>
    <div class="row">
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
          <li><a href="#">Category Name</a></li>
        </ul>
      </div>
    </div>
 <!-- /.row -->
  </div>
 <!-- Side Widget Well -->


  <div class="well">
   <h4>Recent Articles</h4>
    <% @articles.each do |article| %>
      Created by <%= article.user.username %><br>
      <strong><%= link_to article.title, article %></strong>
      <p><%= truncate(article.body) %></p>
    <% end %>
  </div>
 </div>
</div>